{"uuid": "1102ce31-be7e-4fe1-863b-d782feafc28c", "children": ["34b1a675-498b-4398-bf8d-127992f284a8"], "befores": [{"name": "client", "status": "broken", "statusDetails": {"message": "KeyError: 'endpoint'\n", "trace": "  File \"/opt/anaconda3/envs/untitled/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/anaconda3/envs/untitled/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/anaconda3/envs/untitled/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/anaconda3/envs/untitled/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/anaconda3/envs/untitled/lib/python3.10/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/nandeeshr/Coding/Automation/ApiAutomationPractice1/conftest.py\", line 22, in client\n    response = handler.post(config['auth']['endpoint'], json=config['auth']['payload'])\n"}, "start": 1757472413841, "stop": 1757472413841}], "start": 1757472413841, "stop": 1757472413862}